version: '3.8'

services:
  storage-dashboard:
    build: 
      context: .
      dockerfile: Dockerfile.minimal
    ports:
      - "3001:3001"
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
    extra_hosts:
      - "www.googleapis.com:142.250.185.106"
      - "googleapis.com:142.250.185.106"
      - "accounts.google.com:142.250.185.106"
      - "sheets.googleapis.com:142.250.185.106"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
      - GOOGLE_CREDENTIALS_BASE64=${GOOGLE_CREDENTIALS_BASE64}
      - SYNC_INTERVAL_MINUTES=${SYNC_INTERVAL_MINUTES:-5}
    volumes:
      - storage-data:/app/data:Z
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - label=disable

  # Optional: nginx reverse proxy for production
  nginx:
    image: docker.io/nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro,Z
    depends_on:
      - storage-dashboard
    restart: unless-stopped
    profiles:
      - production
    security_opt:
      - label=disable

volumes:
  storage-data:
    driver: local