apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-dashboard-data
  labels:
    app: storage-dashboard
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # Use default storage class
  # storageClassName: "" # Uncomment and set if you need a specific storage class
