apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-dashboard-data
  labels:
    app: storage-dashboard
    component: data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""  # Use default storage class or specify your preferred storage class